#!/bin/sh

configure_zsh() {
    # Stop if zsh is not present
    if [ ! -x /usr/bin/zsh ]; then
	return
    fi
    # Stop if user has opted out of zsh
    if echo "${LIVE_CONFIG_CMDLINE}" | grep -qs 'nozsh'; then
	return
    fi
    chsh --shell /usr/bin/zsh ali
    chsh --shell /usr/bin/zsh root
}

configure_usergroups() {
    # Ensure those groups exist
    addgroup --system kaboxer || true
    addgroup --system wireshark || true

    # adm - read access to log files
    # dialout - for serial port access
    # kaboxer - for kaboxer
    # vboxsf - shared folders for virtualbox guest
    # wireshark - capture sessions without being root
    ali_groups="adm dialout kaboxer vboxsf wireshark"

    for grp in $ali_groups; do
	getent group $grp >/dev/null || continue
	usermod -a -G $grp ali
    done
}

# Avoid configuring multiple times in case persistence is enabled
if [ -e /var/lib/live/config/ali-user-setup ]; then
    exit 0
    

# Set "ali" as password for the use ali
usermod -p '69OiNvXbDFqy2' ali

# Change default shell to zsh
configure_zsh

# Add ali user to additional groups
configure_usergroups

# Remember that this script has been run
touch /var/lib/live/config/ali-user-setup
